sudo: required
language: node_js
cache:
  directories:
    - node_modules
services:
  - redis-server
notifications:
  email: false
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
env:
  - CXX=g++-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
before_install:
  - npm i -g npm@^2.0.0
  - npm i -g node-gyp
before_script:
  - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
